### ISSUE TITLE
New Loader and Favicon

### ISSUE THREAD

**Issue by jvsinghk** [jvsinghk/spacex#8]
You can add an appropriate loader according to SpaceX programs.
Like spaceship launching.

**Comment by jenndroid** [comment]
could I have a go at this please?

**Comment by jvsinghk** [comment]
Sure @jenndroid let me assign it to you

**Comment by jvsinghk** [comment]
@jenndroid why you closed your PR. I was just reviewing it.

**Comment by jenndroid** [comment]
Oh sorry, I had Prettier turned on when I was making the commit and it added a lot of brackets etc to the code, so I closed it and re-submitted just now.

**Comment by jvsinghk** [comment]
@jenndroid Ohh okay, thanks for removing the prettier changes. I have tested it worked great animation. It would be better if we can remove the white background from it It should be of a smaller size that will work for mobile, tablet, and desktop views and maybe we can add the same or something similar to favicon.

**Comment by jenndroid** [comment]
Cool, I'll work on those now

**Comment by jvsinghk** [comment]
@jenndroid I have added the review make those changes and resolve the conversation in #12

**Comment by jenndroid** [comment]
Done!

**Comment by jvsinghk** [comment]
Great,  I have reviewed it. Looks great thanks to you @jenndroid. Can you please attach the Screenshots in the PR? Any update on the favicon.ico for the same?

**Comment by jvsinghk** [comment]
@jendroid can you please check if you forgot to commit the favicon changes in the PR #12

**Comment by jenndroid** [comment]
The favicon is added to commit 95583fa- the React favicon was binned and replaced with the new one, a SpaceX patch

**Comment by jvsinghk** [comment]
@jenndroid Thanks for contributing. Stay Connected and Stay Safe. Happy Hacking!
